### ISSUE TITLE
Koishi v2 is coming 🎉

### ISSUE THREAD

**Issue by Shigma** [koishijs/koishi#26]
# Work Items

## Infrastructure
- [x] [ws-reverse support](https://github.com/koishijs/koishi/issues/43)
- [x] [go-cqhttp support](https://github.com/koishijs/koishi/issues/32)
- [x] reusable server

## Context API
- [x] standalone hook API
- [x] middleware stack trace
- [x] [new scope API](https://github.com/koishijs/koishi/issues/45)
- [x] [disposable plugin](https://github.com/koishijs/koishi/issues/52)

## Session API

- [x] queued sender
- [x] session observer
- [x] command operations
- [x] session middleware & prompt API

## Command API
- [x] functional user/group fields
- [x] special options
- [x] typed options
- [x] option validators
- [x] better error display
- [x] custom terminator

## Internal Features
- [x] built-in user/group fields adjustments
- [x] built-in help command
- [x] decouple shortcut API
- [x] decouple suggestion API
- [x] decouple validation API

## Lifecycle & Modularization
- [x] single app instance
- [x] lifecycle event adjustments
- [x] migrate database to plugins

## Utility & CLI
- [x] logger API integration
- [x] date API for built-in plugins
- [x] enhanced process management

## Unit Test
- [x] basic support
- [ ] self-testing
  - [ ] koishi-core
  - [x] koishi-utils
  - [x] koishi-test-utils
  - [ ] koishi-plugin-common

## Documentation
- [ ] handbook
- [ ] API references
- [ ] migration guide

## koishi-plugin-mysql
- [x] custom getters
- [ ] custom type casting
- [x] automatically creating tables and columns

## koishi-plugin-mongo

A lot thanks to @masnn

## koishi-plugin-common
- [x] remove exec/exit command
- [ ] integrate more sender APIs
- [ ] info command update
- [x] admin command update
- [x] options.blacklist
- [x] options.throttle

## koishi-plugin-teach
- [x] basic support
- [x] support escape character
- [x] shortcut syntax
- [x] context mechanism
- [x] permission system
- [x] appellation mode
- [x] regexp matcher
- [x] command interpolation
- [x] predecessor and successor
- [x] throttle and prevent loop
- [x] static image server
- [x] review and revert

## koishi-plugin-status
- [x] basic support
- [x] status server
- [ ] status database

## koishi-plugin-schedule
- [x] basic support
- [x] support time offset
- [x] support time unit
- [ ] support max times

**Comment by Shigma** [comment]
# Work Items

## Hook API
- [x] basic support
- [ ] event adjustments

## Adapter API
- [ ] websocket reconnect event
- [ ] basic support (cooperate with test utilities)
- [ ] support [coolq-http-api](https://github.com/richardchien/coolq-http-api)
- [ ] (?) support [qqlight-websocket](https://github.com/Chocolatl/qqlight-websocket)

## Command API
- [ ] support functional user/group fields
- [ ] support regexp-typed shortcut

## Utilities & Internal Plugins
- [x] support `user.name` property
- [x] support `getSenderName`, `getSessionId`, `getContextId`
- [ ] built-in help command with advanced features
- [x] decouple suggestion and validation API
- [x] support `appOptions.throttle`
- [ ] command intention API (cooperate with NLP plugin)

## Lifecycle & Modularization
- [x] support pluggable injections
- [x] support `onApp`
- [ ] enhance database API

## CLI
- [ ] better support for multiple apps
- [ ] more built-in plugins (teach, schedule, recorder, status)
- [ ] (?) support `koishi plugin` command

## Database Support
### MySQL
- [ ] custom type casting
- [ ] automatically creating tables and columns

## Plugin Support
### koishi-plugin-common
- [ ] remove exec/exit command
- [ ] support more sender APIs

### koishi-plugin-teach
- [x] basic support (teach, search, modify, show)
- [x] support escape character ($)
- [x] shortcut syntax (#, #id, ##, ###)
- [x] context mechanism (-e, -E, -d, -D, -g, -G)
- [x] permission system (-w, -W, -f, -F)
- [ ] appellation matcher
- [ ] keyword and regexp matcher
- [ ] predecessor and successor (<<, <<<, >>, >>>)
- [x] throttle and prevent loop

### koishi-plugin-status
- [x] basic support
- [ ] status server

### koishi-plugin-schedule
- [x] basic support
- [ ] support time offset
- [ ] support time unit

### koishi-plugin-recorder
- [ ] basic support
- [ ] find message records

### koishi-plugin-nlp
- [ ] cooperate with intention API
